# Generated by Django 2.2 on 2021-07-16 20:53

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='apartment_address',
            field=models.CharField(default='apartment address', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='countries',
            field=django_countries.fields.CountryField(default='United States', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='zip',
            field=models.CharField(default='11111', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BillingAddress'),
        ),
    ]
